# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LXDY' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for LXDY

  target 'LXDYTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'LXDYUITests' do
    inherit! :search_paths
    # Pods for testing
  end
  pod 'Alamofire'
  pod 'Kingfisher'

end
